.PHONY : default
default:
	@echo "make msg"
	@echo "--------------"
	@echo "it will compile de messages files..."
	@echo
	@echo
	@echo
	@echo


.PHONY : msg
msg:
	find . -name '*.msg' | xargs python tools/build_msg.py

